### ISSUE TITLE
Pngquant failed to build, make sure that libpng is installed

### ISSUE THREAD

**Issue by linneati** [toddhgardner/perf-training-website#2]
I'm taking the web performance fundamentals course on frontendmasters but I can't install the dependencies in this repo and therefore can't do the exercise. When running `npm install ` I get the following error 

`npm ERR! pngquant pre-build test failed`
`npm ERR! Error: pngquant failed to build, make sure that libpng is installed`

**Comment by toddhgardner** [comment]
I don't see this issue locally. make sure you are running the correct nodejs & npm versions, 18.12.1, 8.19.2

**Comment by butkovv** [comment]
I've got the same issue while trying to run this on MacOS Ventura 13.4.1 with yarn, even with correct nodejs & npm versions.

**Comment by Akshat42** [comment]
I got the same issue even with correct versions of npm and nodeJs

**Comment by toddhgardner** [comment]
Sorry your having trouble. This training has been upgraded and replaced with a new course:

https://frontendmasters.com/courses/web-perf-v2/

There is a new repo with updated examples.
